//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalAndroid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniversalAndroid.Resources.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAACbSURBVHja7JdRCsAgDEMb8YDe/zLd14YbuLlYrBvtl6iQZzUtopQiVajMCeyDPFn4elAkcY7kcPpTJpbIQAAEwGcAUFcwg310BkCuDQPogxCYnvI2Ay0ISpy9Ar25b53lAu2c+28dgIUDLGyoHe4wBWg9OBoiGYgPQSQjB9BOyEbCNES04wAIgCUA4Kh/fE49ICAisgEAAP//AwBVsBg3MADr8QAAAABJRU5ErkJggg==.
        /// </summary>
        internal static string CLOSE_WINDOW {
            get {
                return ResourceManager.GetString("CLOSE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAACaSURBVHja7JdLDoAgDEQ7hPtfeVxpwATFUimadsUvmdfCQABJKaLqvBjYG3my8DlRJHGO5JB9VYklKhAAAfAZAJQ3mME6dQWgnBsG4I0QNG/K0wq0IFTi2i3gxX5zlgvYOfbfewAWDrCwITvcYQrQOnBqiGQgPgSRjBygdkI2ElZDxHMcAAGwBAAc9Y/PqQcEREQ2AAAA//8DAGUlGkRWn56aAAAAAElFTkSuQmCC.
        /// </summary>
        internal static string CLOSE_WINDOW_HOVER {
            get {
                return ResourceManager.GetString("CLOSE_WINDOW_HOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAI8AAAAqCAYAAACKsgjOAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMBAPh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOcqAAB4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DARKGRAY_BUTTON {
            get {
                return ResourceManager.GetString("DARKGRAY_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAI8AAAAqCAYAAACKsgjOAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXXPues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMBAPh+PDwrIsAHvgABeNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAtAGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5ANgtADBJV2ZIALC3AMDOEAuyAAgMADBRiIUpAAR7AGDIIyN4AISZABRG8lc88SuuEOcqAAB4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DARKGRAY_BUTTON_HOVER {
            get {
                return ResourceManager.GetString("DARKGRAY_BUTTON_HOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAABqSURBVHja7Je7DQAhDENtxIDZfxmuAgHVFQiDsKt0efkrjAh0KtgjViNvdjwHygSxkiD6IRNHZMAAbwPkvwtj0dy7BPf1wIo7QZfAAAYwwPWbkEqA4h4wwBMAFPpvz6kCggDwAQAA//8DAHGVCTsefcymAAAAAElFTkSuQmCC.
        /// </summary>
        internal static string MINIMIZE_WINDOW {
            get {
                return ResourceManager.GetString("MINIMIZE_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAABqSURBVHja7Jc7DsAgDENtxP2vHKZWhYkBaiLsKUx5+QtGBD7qHhvFx6g/Ox4DZYFYRRB9l4kjMmCAuwHq7MJYNPcuQb4eWHEn6BIYwAAGSL8JqQQI94ABrgCg0P/7OVVAEAAaAAAA//8DAIEKC0g4hjOBAAAAAElFTkSuQmCC.
        /// </summary>
        internal static string MINIMIZE_WINDOW_HOVER {
            get {
                return ResourceManager.GetString("MINIMIZE_WINDOW_HOVER", resourceCulture);
            }
        }
    }
}
